### ISSUE TITLE
Access Kubernetes resources using AWS SSO credentials

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#617]
## Description

As a developer,
I want to access Kubernetes resources using my AWS single sign-on (SSO) account,
so that I do not need long lived IAM credentials in my account,
which will make access to the Kubernetes cluster more secure.

## Acceptance Criteria** (Definition of done) 

- [x] Can view Kubernetes resources using `kubectl` using AWS SSO credentials.
- [x] Can view Kubernetes resources in the AWS EKS console.

## QA Steps

- [x] Using AWS SSO credentials, run `kubectl get pods -n notification-canada-ca` from a command line and see the pods that are deployed.
- [x] In the AWS console, view the [EKS workflows and nodes](https://ca-central-1.console.aws.amazon.com/eks/home?region=ca-central-1#/clusters/notification-canada-ca-staging-eks-cluster?selectedTab=cluster-workloads-tab).

**Comment by patheard** [comment]
This can be done by adding the AWS SSO role ARNs to the k8s `configmap/aws-auth` resource:
```sh
# backup the configmap
kubectl get configmap aws-auth -n kube-system -o yaml > configmap-aws-auth.yaml

# edit to add the AWS SSO role ARNs
kubectl edit configmap aws-auth -n kube-system         
```

Staging has been setup and tested for Admin access by adding the following role:
```yaml
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::${ACCOUNT_ID}:role/AWSReservedSSO_AdministratorAccess_${UNIQUE_ROLE_ID}
      username: AWSAdministratorAccess:{{SessionName}}
```
